import html from "../template/proforma-invoice-real.html?raw";

export enum ItemColumn {
  DescriptionTH = "DescriptionTH",
  DescriptionEN = "DescriptionEN",
  Photo = "Photo",
  MadeFrom = "MadeFrom",
  HSCode = "HSCode",
  Qty = "Qty",
  Unit = "Unit",
  UnitPrice = "UnitPrice",
  TotalPrice = "TotalPrice",
  Gw = "Gw",
  Nw = "Nw",
  Note = "Note",
  Additional1 = "Additional1",
  Additional2 = "Additional2",
}

export const mapperHeaderName = {
  [ItemColumn.DescriptionEN]: "PRODUCT NAME (ENG)",
  [ItemColumn.DescriptionTH]: "PRODUCT NAME (THAI)",
  [ItemColumn.MadeFrom]: "MADE FROM",
  [ItemColumn.HSCode]: "HS CODE",
  [ItemColumn.Qty]: "QTY",
  [ItemColumn.Unit]: "UNIT",
  [ItemColumn.UnitPrice]: "UNIT PRICE (THB)",
  [ItemColumn.TotalPrice]: "TOTAL PRICE (THB)",
  [ItemColumn.Gw]: "GW",
  [ItemColumn.Nw]: "NW",
  [ItemColumn.Note]: "NOTE",
  [ItemColumn.Additional1]: "ADDITIONAL 1",
  [ItemColumn.Additional2]: "ADDITIONAL 2",
  [ItemColumn.Photo]: "PHOTO",
};

interface ProformaItemInputType {
  descriptionTH: string;
  descriptionEN: string;
  madeFrom: string;
  hsCode: string;
  qty: number;
  unitTypeId: string;
  unitPrice: number;
  currencyId: string;
  exRate: number;
  nw: number;
  gw: number;
  additional1: string;
  additional2: string;
  note: string;
  photoId: string;
}

type test = ProformaItemInputType & { totalPrice: number };

export const columnMapItemKeys: {
  [key: string]: keyof test;
} = {
  [ItemColumn.DescriptionTH]: "descriptionTH",
  [ItemColumn.DescriptionEN]: "descriptionEN",
  [ItemColumn.Photo]: "photoId",
  [ItemColumn.MadeFrom]: "madeFrom",
  [ItemColumn.HSCode]: "hsCode",
  [ItemColumn.Qty]: "qty",
  [ItemColumn.Unit]: "unitTypeId",
  [ItemColumn.UnitPrice]: "unitPrice",
  [ItemColumn.Gw]: "gw",
  [ItemColumn.Nw]: "nw",
  [ItemColumn.Note]: "note",
  [ItemColumn.Additional1]: "additional1",
  [ItemColumn.Additional2]: "additional2",
  [ItemColumn.TotalPrice]: "totalPrice",
};

const allColumns = [
  "DescriptionEN",
  "DescriptionTH",
  "Photo",
  "MadeFrom",
  "HSCode",
  "Qty",
  "Unit",
  "UnitPrice",
  "TotalPrice",
  "Gw",
  "Nw",
  "Note",
  "Additional1",
  "Additional2",
] as ItemColumn[];

const chunkArray = (array: any[], chunkSize: number) => {
  for (let i = 0; i < array.length; i += chunkSize) {
    const chunk = array.slice(i, i + chunkSize);
    return chunk;
  }
};

export const ProformaInvoice = () => {
  const rawItems = [
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Box",
      descriptionTH: "กล่อง",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 20,
      unitPrice: 20,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Box",
      descriptionTH: "กล่อง",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 20,
      unitPrice: 20,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Box",
      descriptionTH: "กล่อง",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 20,
      unitPrice: 20,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Box",
      descriptionTH: "กล่อง",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 20,
      unitPrice: 20,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Box",
      descriptionTH: "กล่อง",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 20,
      unitPrice: 20,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Box",
      descriptionTH: "กล่อง",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 20,
      unitPrice: 20,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Box",
      descriptionTH: "กล่อง",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 20,
      unitPrice: 20,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Box",
      descriptionTH: "กล่อง",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 20,
      unitPrice: 20,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Box",
      descriptionTH: "กล่อง",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 20,
      unitPrice: 20,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Box",
      descriptionTH: "กล่อง",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 20,
      unitPrice: 20,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Box",
      descriptionTH: "กล่อง",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 20,
      unitPrice: 20,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Box",
      descriptionTH: "กล่อง",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 20,
      unitPrice: 20,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
    {
      currencyId: "test",
      descriptionEN: "Shoe",
      descriptionTH: "รองเท้า",
      exRate: 1,
      gw: 0,
      nw: 0,
      qty: 10,
      unitPrice: 10,
      unitType: "UNIT",
    },
  ];

  const columnsTransform = allColumns.map((col) => ({
    title: mapperHeaderName[col],
    key: columnMapItemKeys[col],
    col,
  }));

  const data = {
    imageLogo: "images/logo-cpl-black.png",
    fontInter: "fonts/Inter-Regular.ttf",
    fontInterBold: "fonts/Inter-Bold.ttf",
    fontInterSemiBold: "fonts/Inter-SemiBold.ttf",
    fontInterMedium: "fonts/Inter-Medium.ttf",
    shownColumns: allColumns,
    columns: columnsTransform,
    items: [
      {
        additional1: "",
        additional2: "",
        currencyId: "test",
        descriptionEN: "gold",
        descriptionTH: "ทอง",
        exRate: 1,
        gw: 10,
        hsCode: "ggg",
        madeFrom: "gold",
        note: "",
        nw: 10,
        photoId: "64796266e3427f5db7ea7d84",
        qty: 10,
        unitPrice: 10,
        unitTypeId: "test",
        photoUrl:
          "https://mycpl-v3.s3.amazonaws.com/20230602/Duelist_1685676645873.png?AWSAccessKeyId=AKIAXV4VO5AOR6Z2XTHZ&Expires=1685862463&Signature=DQkQFGHRoWbVd85CfkQi8hRlNZY%3D",
      },
      {
        additional1: "",
        additional2: "",
        currencyId: "test",
        descriptionEN: "aa",
        descriptionTH: "",
        exRate: 1,
        gw: 0,
        hsCode: "",
        madeFrom: "",
        note: "",
        nw: 0,
        photoId: "6479626de3427f5db7ea7d85",
        qty: 20,
        unitPrice: 20,
        unitTypeId: "test",
        photoUrl:
          "https://mycpl-v3.s3.amazonaws.com/20230602/heart_1685676652709.png?AWSAccessKeyId=AKIAXV4VO5AOR6Z2XTHZ&Expires=1685862463&Signature=4GPzfuvm3jecQ9rUqD0bscrT9rM%3D",
      },
      {
        additional1: "",
        additional2: "",
        currencyId: "test",
        descriptionEN: "bb",
        descriptionTH: "",
        exRate: 1,
        gw: 0,
        hsCode: "",
        madeFrom: "",
        note: "",
        nw: 0,
        photoId: "64796274e3427f5db7ea7d86",
        qty: 30,
        unitPrice: 30,
        unitTypeId: "test",
        photoUrl:
          "https://mycpl-v3.s3.amazonaws.com/20230602/Lazor_1685676660284.png?AWSAccessKeyId=AKIAXV4VO5AOR6Z2XTHZ&Expires=1685862463&Signature=odtNZoX9WvcXgXJip2RolK4DdLc%3D",
      },
      {
        additional1: "",
        additional2: "",
        currencyId: "test",
        descriptionEN: "cc",
        descriptionTH: "",
        exRate: 1,
        gw: 0,
        hsCode: "",
        madeFrom: "",
        note: "",
        nw: 0,
        photoId: "647962c3e3427f5db7ea7d88",
        qty: 40,
        unitPrice: 40,
        unitTypeId: "test",
        photoUrl:
          "https://mycpl-v3.s3.amazonaws.com/20230602/Mage_1685676739421.png?AWSAccessKeyId=AKIAXV4VO5AOR6Z2XTHZ&Expires=1685862463&Signature=dKbM4YUW0%2BQdb6bHAFaa2qpZ58A%3D",
      },
    ],
    noteAndInstruction: {},
  };

  const template = Handlebars.compile(html);
  const htmlString = template(data);

  return <div dangerouslySetInnerHTML={{ __html: htmlString }} />;
};
