import html from '../template/test.html?raw';
// import html from '../template/sale-invoice.html?raw';
import * as Handlebars from 'handlebars';

type Service = {
  name: string;
  description: string;
  qty: string;
  unit: string;
  unitPrice: string;
  discount: string;
  vat7: string;
  vat0: string;
  nonVat: string;
  whtPercent: string;
  whtValue: string;
};

type SaleInvoiceTemplateData = {
  imageLogo: string;
  documentNo: string;
  customerCode: string;
  orderDate: string;
  branch: string;
  jobNo: string;
  sales: string;
  billTo: string;
  billAddress: string;
  billTel: string;
  billTax: string;
  remark: string;
  subTotalVat7: string;
  subTotalVat0: string;
  subTotalNonVat: string;
  vatVat7: string;
  vatVat0: string;
  vatNonVat: string;
  grandTotalVat7: string;
  grandTotalVat0: string;
  grandTotalNonVat: string;
  whtAmountVat7: string;
  whtAmountVat0: string;
  whtAmountNonVat: string;
  total: string;
  creditFee: string;
  totalPayableIncludeCreditFee: string;
  internationalTransferFee: string;
  totalPayableIncludeInternationalTransferFee: string;
  services: Service[];
  isWht: boolean;
};

export const SaleInvoice = () => {
  const data = {
    imageLogo: '/images/cpl.png',
    billTo: 'Aey-1',
    billAddress: '222, 123/2, 5555, 123, SOUTH KOREA',
    billTel: '+82 08333333',
    billTax: '222',
    documentNo: 'SI230710000001',
    customerCode: '000087',
    orderDate: '23/07/17',
    branch: 'CPLEx in Singapore',
    jobNo: '2307100001',
    sales: 'KANYAKORN THAPANANAN',
    remark: '33.00',
    subTotalVat7: '33.00',
    subTotalVat0: '33.00',
    subTotalNonVat: '33.00',
    vatVat7: '33.00',
    vatVat0: '33.00',
    vatNonVat: '33.00',
    grandTotalVat7: '33.00',
    grandTotalVat0: '33.00',
    grandTotalNonVat: '33.00',
    whtAmountVat7: '33.00',
    whtAmountVat0: '33.00',
    whtAmountNonVat: '33.00',
    total: '22.00',
    creditFee: '3',
    totalPayableIncludeCreditFee: '33.07',
    internationalTransferFee: '450.00',
    totalPayableIncludeInternationalTransferFee: '482.10',
    services: [
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
      {
        name: 'AIR COURIER : EXPRESS (DOCUMENT)',
        description: 'ACD-TNT',
        qty: '1.00',
        unit: 'KG',
        unitPrice: '30.00',
        discount: '0.00',
        vat7: '0.00',
        vat0: '0.00',
        nonVat: '0.00',
        whtPercent: '1',
        whtValue: '12',
      },
    ],
    isWht: true,
  };

  const template = Handlebars.compile(html);
  const htmlString = template(data);

  return <div dangerouslySetInnerHTML={{ __html: htmlString }} />;
};
